theme: Minimal

title: "Your Name"
description: "PhD Student | Computational Imaging | Research"
baseurl: "" # Leave empty if using username.github.io
url: "https://dshyamsingh.github.io"

theme: minima  # or another Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Your Name"
  email: "your.email@example.com"
  github: "yourgithubusername"
  linkedin: "yourlinkedin"

markdown: kramdown
permalink: pretty

